"""Verified CORNARE challenge facts.

Values here were read from the local CLIMATERISK brief and deck on 2026-10-07.
They are the Level 1 institutional record. Do not replace them with external numbers.
"""

from __future__ import annotations

BUDGET_MILLION_COP = 5000

DIMENSIONS = [
    {
        "id": "biodiversity",
        "name": "Biodiversidad y servicios ecosistémicos",
        "short_name": "Biodiversidad",
    },
    {
        "id": "water",
        "name": "Recurso hídrico",
        "short_name": "Recurso hídrico",
    },
    {
        "id": "disaster",
        "name": "Riesgo de desastres",
        "short_name": "Riesgo de desastres",
    },
    {
        "id": "health",
        "name": "Salud humana",
        "short_name": "Salud",
    },
    {
        "id": "infrastructure",
        "name": "Infraestructura",
        "short_name": "Infraestructura",
    },
    {
        "id": "habitat",
        "name": "Hábitat humano",
        "short_name": "Hábitat",
    },
    {
        "id": "food",
        "name": "Seguridad alimentaria",
        "short_name": "Seguridad alimentaria",
    },
]

MUNICIPALITIES = [
    {
        "id": "rionegro",
        "name": "Rionegro",
        "divipola": "05615",
        "department": "Antioquia",
        "subregion": "Valles de San Nicolás",
    },
    {
        "id": "guarne",
        "name": "Guarne",
        "divipola": "05318",
        "department": "Antioquia",
        "subregion": "Valles de San Nicolás",
    },
    {
        "id": "marinilla",
        "name": "Marinilla",
        "divipola": "05440",
        "department": "Antioquia",
        "subregion": "Valles de San Nicolás",
    },
]

# Slide 12 of HACKATHON RETO CORNARE.pptx. Column headers are dimension names.
# The closing line of that slide asks for territorial vulnerability, and the
# biodiversity cells match the brief's vulnerability classes. They do not match
# Rionegro's disaster-risk class (Bajo → Medio), so these cells are vulnerability.
VULNERABILITY_CLASS = {
    "rionegro": {
        "disaster": "alta",
        "habitat": "muy_baja",
        "water": "media",
        "infrastructure": "media",
        "health": "muy_baja",
        "biodiversity": "muy_alta",
        "food": "baja",
    },
    "guarne": {
        "disaster": "alta",
        "habitat": "baja",
        "water": "media",
        "infrastructure": "alta",
        "health": "baja",
        "biodiversity": "media",
        "food": "baja",
    },
    "marinilla": {
        "disaster": "muy_baja",
        "habitat": "baja",
        "water": "alta",
        "infrastructure": "muy_baja",
        "health": "baja",
        "biodiversity": "muy_alta",
        "food": "muy_baja",
    },
}

CLASS_LABELS = {
    "muy_baja": "Muy baja",
    "baja": "Baja",
    "media": "Media",
    "alta": "Alta",
    "muy_alta": "Muy alta",
}

# Numeric findings stated in RETO CLIMATE WEEK HACKATHON.pdf. No other numbers
# from that family are encoded.
NUMERIC_FINDINGS = [
    {
        "id": "rio-bio-vuln",
        "municipality_id": "rionegro",
        "dimension_id": "biodiversity",
        "metric": "vulnerability",
        "scenario": "reference",
        "year": None,
        "value": 0.75,
        "value_min": None,
        "value_max": None,
        "classification": "muy_alta",
        "provenance": "institutional",
        "source_id": "reto-brief-2026",
        "note": "El reto indica vulnerabilidad 0,75 (Muy alta).",
    },
    {
        "id": "mar-bio-vuln",
        "municipality_id": "marinilla",
        "dimension_id": "biodiversity",
        "metric": "vulnerability",
        "scenario": "reference",
        "year": None,
        "value": 0.72,
        "value_min": None,
        "value_max": None,
        "classification": "muy_alta",
        "provenance": "institutional",
        "source_id": "reto-brief-2026",
        "note": "El reto indica vulnerabilidad 0,72 (Muy alta).",
    },
    {
        "id": "region-bio-vuln",
        "municipality_id": None,
        "geography": "regional",
        "dimension_id": "biodiversity",
        "metric": "vulnerability",
        "scenario": "reference",
        "year": None,
        "value": 0.55,
        "value_min": None,
        "value_max": None,
        "classification": None,
        "provenance": "institutional",
        "source_id": "reto-brief-2026",
        "note": "Promedio regional de vulnerabilidad en biodiversidad. No es un valor municipal.",
    },
    {
        "id": "region-water-vuln",
        "municipality_id": None,
        "geography": "regional",
        "dimension_id": "water",
        "metric": "vulnerability",
        "scenario": "reference",
        "year": None,
        "value": 0.53,
        "value_min": None,
        "value_max": None,
        "classification": None,
        "provenance": "institutional",
        "source_id": "reto-brief-2026",
        "note": "Promedio regional de vulnerabilidad en recurso hídrico. No es un valor municipal.",
    },
    {
        "id": "rio-bio-ac",
        "municipality_id": "rionegro",
        "dimension_id": "biodiversity",
        "metric": "adaptive_capacity",
        "scenario": "reference",
        "year": None,
        "value": 0.22,
        "value_min": None,
        "value_max": None,
        "classification": None,
        "provenance": "institutional",
        "source_id": "reto-brief-2026",
        "note": "Capacidad adaptativa en biodiversidad. El reto no asigna clase a este 0,22; la clase Muy baja no se infiere.",
    },
    {
        "id": "mar-bio-ac",
        "municipality_id": "marinilla",
        "dimension_id": "biodiversity",
        "metric": "adaptive_capacity",
        "scenario": "reference",
        "year": None,
        "value": 0.24,
        "value_min": None,
        "value_max": None,
        "classification": None,
        "provenance": "institutional",
        "source_id": "reto-brief-2026",
        "note": "Capacidad adaptativa en biodiversidad.",
    },
    {
        "id": "gua-bio-ac",
        "municipality_id": "guarne",
        "dimension_id": "biodiversity",
        "metric": "adaptive_capacity",
        "scenario": "reference",
        "year": None,
        "value": 0.33,
        "value_min": None,
        "value_max": None,
        "classification": "baja",
        "provenance": "institutional",
        "source_id": "reto-brief-2026",
        "note": "El reto dice que 0,33 en biodiversidad sigue en categoría Baja.",
    },
    {
        "id": "rio-drm-ac",
        "municipality_id": "rionegro",
        "dimension_id": "disaster",
        "metric": "adaptive_capacity",
        "scenario": "reference",
        "year": None,
        "value": 0.56,
        "value_min": None,
        "value_max": None,
        "classification": None,
        "provenance": "institutional",
        "source_id": "reto-brief-2026",
        "note": "Capacidad adaptativa relativamente favorable en gestión del riesgo. No es la vulnerabilidad de la dimensión.",
    },
    {
        "id": "mar-drm-ac",
        "municipality_id": "marinilla",
        "dimension_id": "disaster",
        "metric": "adaptive_capacity",
        "scenario": "reference",
        "year": None,
        "value": 0.61,
        "value_min": None,
        "value_max": None,
        "classification": None,
        "provenance": "institutional",
        "source_id": "reto-brief-2026",
        "note": "Capacidad adaptativa relativamente favorable en gestión del riesgo.",
    },
    {
        "id": "mar-disaster-threat",
        "municipality_id": "marinilla",
        "dimension_id": "disaster",
        "metric": "threat",
        "scenario": "reference",
        "year": None,
        "value": None,
        "value_min": 0.66,
        "value_max": 0.73,
        "classification": "alta",
        "provenance": "institutional",
        "source_id": "reto-brief-2026",
        "note": "Amenaza, no vulnerabilidad ni riesgo. El reto da un rango 0,66–0,73 (Alta).",
    },
    {
        "id": "rio-disaster-sensitivity",
        "municipality_id": "rionegro",
        "dimension_id": "disaster",
        "metric": "sensitivity",
        "scenario": "reference",
        "year": None,
        "value": 0.40,
        "value_min": None,
        "value_max": None,
        "classification": None,
        "provenance": "institutional",
        "source_id": "reto-brief-2026",
        "note": "Mayor sensibilidad del corredor en riesgo de desastres. El reto no publica la clase de este 0,40.",
    },
    {
        "id": "rio-disaster-risk-ref",
        "municipality_id": "rionegro",
        "dimension_id": "disaster",
        "metric": "risk",
        "scenario": "reference",
        "year": None,
        "value": 0.28,
        "value_min": None,
        "value_max": None,
        "classification": "baja",
        "classification_label": "Bajo",
        "provenance": "institutional",
        "source_id": "reto-brief-2026",
        "note": "Riesgo climático de referencia en la dimensión de desastres. La etiqueta del reto es Bajo; la escala interna usa la misma clase que Baja.",
    },
    {
        "id": "rio-disaster-risk-2060",
        "municipality_id": "rionegro",
        "dimension_id": "disaster",
        "metric": "risk",
        "scenario": "ssp3_7_0",
        "year": 2060,
        "value": 0.32,
        "value_min": None,
        "value_max": None,
        "classification": "media",
        "classification_label": "Medio",
        "provenance": "institutional",
        "source_id": "reto-brief-2026",
        "note": "Hacia 2060 el riesgo pasa de 0,28 a 0,32, de Bajo a Medio. Es el único cambio de escenario cuantificado en el reto.",
    },
]

DECISION_PARAMETERS = {
    "budget_million_cop": BUDGET_MILLION_COP,
    "currency_display": "COP millones",
    "costs_indivisible": True,
    "one_functional_unit_per_measure": True,
    "weights": {
        "vulnerability": 0.70,
        "recurrence": 0.15,
        "workshops": 0.15,
    },
    "workshops_scored": False,
    "workshops_note": "La presentación asigna 15% a la recurrencia en talleres municipales. El paquete no trae esos conteos, así que ese término no se imputa.",
    "class_scores": {
        "muy_baja": 0.20,
        "baja": 0.40,
        "media": 0.60,
        "alta": 0.80,
        "muy_alta": 1.00,
    },
    "diminishing_second_measure": {
        "institucional": 0.35,
        "naturaleza": 0.35,
        "multidimensional": 0.15,
        "bajo_arrepentimiento": 0.35,
    },
    "cobenefit_weight": 0.05,
    "recurrence_coverage_min_records": 5,
    "low_regret_full_weight_min_class_score": 0.80,
    "low_regret_other_factor": 0.50,
    "ssp": {
        "scenario": "ssp3_7_0",
        "year": 2060,
        "dimension_id": "disaster",
        "municipality_id": "rionegro",
        "metric": "risk",
        "from_class": "baja",
        "to_class": "media",
        "from_value": 0.28,
        "to_value": 0.32,
        "application": "team_inference",
        "note": "El cambio Bajo → Medio es institucional. Aplicarlo como un escalón de clase sobre las medidas de riesgo de desastres es una inferencia del equipo, acotada a esa dimensión.",
    },
    "lenses": [
        {
            "id": "institucional",
            "name": "Institucional",
            "default": True,
            "summary": "Prioriza la clase de vulnerabilidad y la recurrencia documentada, con cobertura decreciente dentro de la misma dimensión.",
        },
        {
            "id": "naturaleza",
            "name": "Naturaleza positiva",
            "default": False,
            "summary": "Usa el mismo puntaje institucional. La clase de solución basada en la naturaleza solo desempatá portafolios con el mismo puntaje.",
        },
        {
            "id": "multidimensional",
            "name": "Multidimensional robusta",
            "default": False,
            "summary": "Penaliza con más fuerza la segunda medida en una dimensión ya cubierta.",
        },
        {
            "id": "bajo_arrepentimiento",
            "name": "Bajo arrepentimiento",
            "default": False,
            "summary": "Prefiere medidas de menor costo que atienden clases Alta o Muy alta, para no agotar el fondo en una sola obra.",
        },
    ],
    "baselines": [
        {
            "id": "max_count",
            "name": "Máximo número de medidas",
            "summary": "Elige la mayor cantidad de medidas que cabe en el fondo y, entre esas, el mayor puntaje institucional.",
        },
        {
            "id": "grey",
            "name": "Infraestructura gris primero",
            "summary": "Incluye infraestructura resiliente al cambio climático y completa el fondo con el mejor puntaje institucional restante.",
        },
    ],
}

# Phrase match is team inference. Phrases are folded (lowercase, no accents).
MATCH_PHRASES = {
    "bio_psa": ["pago por servicios ambientales", "pagos por servicios ambientales"],
    "bio_restore": ["restauracion de ecosistemas estrategicos"],
    "bio_pa": ["sistemas de areas protegidas", "sistema regional de areas protegidas"],
    "water_eff": ["uso intersectorial eficiente"],
    "water_riparian": ["rondas hidricas"],
    "water_head": ["cabecera de cuencas", "cabeceras de cuenca"],
    "food_soil": ["suelos agricolas estrategicos"],
    "food_agro": ["produccion agroecologica"],
    "hab_green": ["espacios verdes urbanos", "espacios publicos verdes"],
    "hab_suds": ["drenaje sostenible", "drenajes sostenibles"],
    "infra_resilient": ["infraestructura resiliente al cambio climatico"],
    "infra_services": ["servicios publicos para el habitat"],
    "risk_sat": ["alerta temprana", "alertas tempranas"],
    "risk_knowledge": ["conocimiento de las amenazas"],
    "health": ["sistema de salud y entornos saludables", "sistema de salud"],
}


def _measure(**kwargs):
    return kwargs


INTERVENTIONS = [
    _measure(
        id="bio_psa",
        name="Instrumentos de compensación y Pago por Servicios Ambientales – PSA",
        dimension_id="biodiversity",
        cost_million_cop=1200,
        functional_unit="Programa territorial de conservación/restauración de áreas estratégicas durante 3 años",
        type="economic_instrument",
        nbs_class="NBS_DIRECT",
        scope="municipality",
        sensitivity_factors_addressed=["Pérdida y deterioro de ecosistemas estratégicos"],
        adaptive_capacity_factors_strengthened=["Acuerdos de conservación e incentivos a beneficiarios"],
        cobenefit_dimension_ids=[],
        cobenefit_note=None,
        actors=[
            {"name": "CORNARE", "level": "autoridad ambiental"},
            {"name": "Gobiernos municipales", "level": "municipal"},
            {"name": "Comunidades locales", "level": "comunitario"},
            {"name": "Productores", "level": "productivo"},
        ],
        limitations=[
            "El costo es un supuesto homogéneo del reto, no un presupuesto contractual.",
            "Contar beneficiarios no mide la reducción de vulnerabilidad.",
            "No hay predios ni polígonos de implementación en el paquete.",
        ],
        nbs_reason="La unidad funcional del reto es un programa de conservación y restauración. El pago es el instrumento, no el ecosistema. No se afirma que cumpla los ocho criterios IUCN.",
    ),
    _measure(
        id="bio_restore",
        name="Restauración de ecosistemas estratégicos",
        dimension_id="biodiversity",
        cost_million_cop=1500,
        functional_unit="Intervención integral aproximada de 100 ha, incluyendo establecimiento, mantenimiento inicial y seguimiento",
        type="ecosystem_restoration",
        nbs_class="NBS_DIRECT",
        scope="municipality",
        sensitivity_factors_addressed=["Cobertura y condición de ecosistemas estratégicos"],
        adaptive_capacity_factors_strengthened=["Seguimiento y mantenimiento inicial de áreas restauradas"],
        cobenefit_dimension_ids=[],
        cobenefit_note=None,
        actors=[
            {"name": "CORNARE", "level": "autoridad ambiental"},
            {"name": "Administradores de áreas protegidas", "level": "áreas protegidas"},
            {"name": "Comunidades locales", "level": "comunitario"},
        ],
        limitations=[
            "100 ha es la unidad del ejercicio, no un área priorizada con cartografía en este paquete.",
            "No hay un porcentaje de efectividad de restauración.",
        ],
        nbs_reason="El mecanismo principal es restaurar ecosistemas. Es una acción de base ecosistémica. La verificación IUCN del proyecto concreto queda pendiente.",
    ),
    _measure(
        id="bio_pa",
        name="Fortalecimiento de sistemas de áreas protegidas",
        dimension_id="biodiversity",
        cost_million_cop=700,
        functional_unit="Identificación, gestión, acuerdos, conectividad y fortalecimiento de áreas estratégicas en el corredor",
        type="protected_areas",
        nbs_class="NBS_DIRECT",
        scope="corridor",
        sensitivity_factors_addressed=["Fragmentación y debilidad de gestión de áreas estratégicas"],
        adaptive_capacity_factors_strengthened=["Acuerdos y gestión del sistema de áreas protegidas"],
        cobenefit_dimension_ids=[],
        cobenefit_note="El texto dice conectividad, pero no hay una capa de conectividad en el paquete. No se dibujan corredores ecológicos.",
        actors=[
            {"name": "CORNARE", "level": "autoridad ambiental"},
            {"name": "Administradores de áreas protegidas", "level": "áreas protegidas"},
            {"name": "Gobiernos municipales", "level": "municipal"},
        ],
        limitations=[
            "La conectividad se menciona como propósito de la unidad funcional, no como un vínculo espacial demostrado.",
        ],
        nbs_reason="Protege y gestiona ecosistemas. La mención de conectividad no autoriza un mapa de enlaces ecológicos.",
    ),
    _measure(
        id="water_eff",
        name="Uso intersectorial eficiente del recurso hídrico",
        dimension_id="water",
        cost_million_cop=900,
        functional_unit="Programa para grandes usuarios, empresas, sector público y/o productivo: diagnóstico, medición, eficiencia, reúso y seguimiento",
        type="demand_management",
        nbs_class="ENABLING",
        scope="municipality",
        sensitivity_factors_addressed=["Presión de uso sobre la oferta hídrica"],
        adaptive_capacity_factors_strengthened=["Medición, eficiencia y seguimiento de usuarios"],
        cobenefit_dimension_ids=[],
        cobenefit_note=None,
        actors=[
            {"name": "CORNARE", "level": "autoridad ambiental"},
            {"name": "Empresas de servicios públicos y acueductos", "level": "agua"},
            {"name": "Sectores productivos", "level": "productivo"},
            {"name": "Gobiernos municipales", "level": "municipal"},
        ],
        limitations=[
            "No identifica qué empresa depende de cuál fuente. Esa dependencia es una brecha.",
            "Eficiencia hídrica no es una solución basada en la naturaleza.",
        ],
        nbs_reason="El mecanismo es gestión de la demanda y medición. Habilita la adaptación hídrica sin intervenir el ecosistema como acción principal.",
    ),
    _measure(
        id="water_riparian",
        name="Protección y recuperación de rondas hídricas",
        dimension_id="water",
        cost_million_cop=1300,
        functional_unit="Intervención integral de corredores ribereños priorizados: restauración, aislamiento, recuperación y seguimiento",
        type="riparian_restoration",
        nbs_class="NBS_DIRECT",
        scope="municipality",
        sensitivity_factors_addressed=["Deterioro de rondas y corredores ribereños"],
        adaptive_capacity_factors_strengthened=["Planes de manejo y seguimiento de rondas"],
        cobenefit_dimension_ids=[],
        cobenefit_note="La restauración ribereña puede apoyar biodiversidad, pero la unidad funcional no nombra esa dimensión. No se suma un cobeneficio numérico.",
        actors=[
            {"name": "CORNARE", "level": "autoridad ambiental"},
            {"name": "Gobiernos municipales", "level": "municipal"},
            {"name": "Comunidades locales", "level": "comunitario"},
        ],
        limitations=["No hay quebradas priorizadas dentro de Rionegro, Guarne o Marinilla en el catálogo del reto."],
        nbs_reason="Restaura y aísla ecosistemas ribereños. Es de base ecosistémica. Los tramos exactos no están en la fuente.",
    ),
    _measure(
        id="water_head",
        name="Protección de cabeceras de cuenca y ecosistemas abastecedores",
        dimension_id="water",
        cost_million_cop=1600,
        functional_unit="Intervención de una microcuenca o sistema abastecedor estratégico",
        type="headwater_protection",
        nbs_class="NBS_DIRECT",
        scope="municipality",
        sensitivity_factors_addressed=["Presión sobre cabeceras y ecosistemas que abastecen agua"],
        adaptive_capacity_factors_strengthened=["Protección de un sistema abastecedor"],
        cobenefit_dimension_ids=["biodiversity"],
        cobenefit_note="El nombre oficial incluye ecosistemas abastecedores, así que se reconoce un cobeneficio hacia biodiversidad. No es un porcentaje de efectividad.",
        actors=[
            {"name": "CORNARE", "level": "autoridad ambiental"},
            {"name": "Empresas de servicios públicos y acueductos", "level": "agua"},
            {"name": "Comunidades locales", "level": "comunitario"},
        ],
        limitations=["La microcuenca no está nombrada. No se asigna una bocatoma a una empresa."],
        nbs_reason="Protege ecosistemas de cabecera. La microcuenca concreta es una brecha de localización.",
    ),
    _measure(
        id="food_soil",
        name="Protección y reconversión de suelos agrícolas estratégicos",
        dimension_id="food",
        cost_million_cop=1000,
        functional_unit="Programa territorial con productores: asistencia, reconversión, conservación de suelo y agua",
        type="soil_reconversion",
        nbs_class="NBS_DIRECT",
        scope="municipality",
        sensitivity_factors_addressed=["Degradación de suelos agrícolas estratégicos"],
        adaptive_capacity_factors_strengthened=["Asistencia y reconversión productiva"],
        cobenefit_dimension_ids=["water"],
        cobenefit_note="La unidad funcional nombra conservación de suelo y agua.",
        actors=[
            {"name": "Productores agropecuarios", "level": "productivo"},
            {"name": "Gobiernos municipales", "level": "municipal"},
            {"name": "CORNARE", "level": "autoridad ambiental"},
        ],
        limitations=["No se identifican predios ni cultivos específicos del corredor."],
        nbs_reason="La reconversión y la conservación de suelo actúan sobre el ecosistema productivo. No se verificó el estándar IUCN en campo.",
    ),
    _measure(
        id="food_agro",
        name="Producción agroecológica y economía rural resiliente",
        dimension_id="food",
        cost_million_cop=800,
        functional_unit="Programa de asistencia técnica, manejo de suelo, agua, asociatividad y adaptación productiva",
        type="agroecology",
        nbs_class="NBS_DIRECT",
        scope="municipality",
        sensitivity_factors_addressed=["Sensibilidad de la producción rural al clima"],
        adaptive_capacity_factors_strengthened=["Asistencia técnica, asociatividad y manejo de suelo y agua"],
        cobenefit_dimension_ids=["water"],
        cobenefit_note="La unidad funcional nombra manejo de agua.",
        actors=[
            {"name": "Productores agropecuarios", "level": "productivo"},
            {"name": "Gobiernos municipales", "level": "municipal"},
            {"name": "CORNARE", "level": "autoridad ambiental"},
        ],
        limitations=["Los registros históricos miden capacitaciones, familias o asistencias, no vulnerabilidad reducida."],
        nbs_reason="El manejo agroecológico de suelo y agua es una práctica de base ecosistémica. La asociatividad es habilitadora y va dentro de la misma unidad.",
    ),
    _measure(
        id="hab_green",
        name="Espacios verdes urbanos",
        dimension_id="habitat",
        cost_million_cop=1000,
        functional_unit="Corredor o área verde multifuncional con arborización, conectividad y regulación térmica e hídrica",
        type="urban_green",
        nbs_class="NBS_DIRECT",
        scope="municipality",
        sensitivity_factors_addressed=["Déficit de regulación térmica e hídrica en el hábitat urbano"],
        adaptive_capacity_factors_strengthened=["Área verde pública multifuncional"],
        cobenefit_dimension_ids=["water"],
        cobenefit_note="La unidad funcional nombra regulación hídrica. La conectividad urbana no se cartografía.",
        actors=[
            {"name": "Gobiernos municipales", "level": "municipal"},
            {"name": "Comunidades locales", "level": "comunitario"},
            {"name": "CORNARE", "level": "autoridad ambiental"},
        ],
        limitations=["No hay un barrio ni un predio designado."],
        nbs_reason="Arborización y área verde son el mecanismo principal. Sigue siendo una clasificación de tamiz, no una certificación IUCN.",
    ),
    _measure(
        id="hab_suds",
        name="Sistemas Urbanos de Drenaje Sostenible – SUDS",
        dimension_id="habitat",
        cost_million_cop=1800,
        functional_unit="Intervención piloto de escala municipal: jardines de lluvia, zonas de infiltración, pavimentos permeables y almacenamiento",
        type="suds",
        nbs_class="NBS_HYBRID",
        scope="municipality",
        sensitivity_factors_addressed=["Escorrentía y drenaje urbano insuficiente"],
        adaptive_capacity_factors_strengthened=["Piloto de infiltración y almacenamiento"],
        cobenefit_dimension_ids=[],
        cobenefit_note="El drenaje toca el agua urbana, pero la ficha del reto ubica la medida en hábitat y no nombra otra dimensión del estudio. No se suma cobeneficio numérico.",
        actors=[
            {"name": "Gobiernos municipales", "level": "municipal"},
            {"name": "CORNARE", "level": "autoridad ambiental"},
            {"name": "Empresas de servicios públicos", "level": "servicios"},
        ],
        limitations=["Mezcla elementos verdes y obras. No se afirma una reducción de profundidad de inundación."],
        nbs_reason="Combina procesos de infiltración y vegetación con pavimentos y almacenamiento. Por eso es híbrida, no una solución basada en la naturaleza pura ni una obra gris.",
    ),
    _measure(
        id="infra_resilient",
        name="Infraestructura resiliente al cambio climático",
        dimension_id="infrastructure",
        cost_million_cop=2500,
        functional_unit="Adecuación de un punto crítico de infraestructura, vía o servicio priorizado",
        type="grey_infrastructure",
        nbs_class="GREY_INFRASTRUCTURE",
        scope="municipality",
        sensitivity_factors_addressed=["Exposición de un punto crítico de infraestructura"],
        adaptive_capacity_factors_strengthened=["Adecuación de ese punto"],
        cobenefit_dimension_ids=[],
        cobenefit_note=None,
        actors=[
            {"name": "Gobiernos municipales", "level": "municipal"},
            {"name": "Entidades de gestión del riesgo", "level": "riesgo"},
            {"name": "CORNARE", "level": "autoridad ambiental"},
        ],
        limitations=[
            "No se nombra la vía ni el punto crítico.",
            "Una obra vial histórica en Guarne no se trata como esta medida.",
        ],
        nbs_reason="El mecanismo es adecuar infraestructura. Es infraestructura gris.",
    ),
    _measure(
        id="infra_services",
        name="Fortalecimiento de infraestructura resiliente y servicios públicos",
        dimension_id="infrastructure",
        cost_million_cop=2000,
        functional_unit="Intervención focalizada de infraestructura o servicio esencial",
        type="grey_infrastructure",
        nbs_class="GREY_INFRASTRUCTURE",
        scope="municipality",
        sensitivity_factors_addressed=["Fragilidad de un servicio esencial"],
        adaptive_capacity_factors_strengthened=["Continuidad del servicio intervenido"],
        cobenefit_dimension_ids=[],
        cobenefit_note=None,
        actors=[
            {"name": "Gobiernos municipales", "level": "municipal"},
            {"name": "Empresas de servicios públicos", "level": "servicios"},
            {"name": "CORNARE", "level": "autoridad ambiental"},
        ],
        limitations=["El servicio esencial no está identificado. No se infieren dependencias de empresas."],
        nbs_reason="Obra o servicio esencial como mecanismo principal. Infraestructura gris.",
    ),
    _measure(
        id="risk_sat",
        name="Fortalecimiento de Sistemas de Alerta Temprana – SAT",
        dimension_id="disaster",
        cost_million_cop=1200,
        functional_unit="Sistema interoperable para puntos críticos del corredor: instrumentación, comunicaciones y protocolos",
        type="early_warning",
        nbs_class="ENABLING",
        scope="corridor",
        sensitivity_factors_addressed=[],
        adaptive_capacity_factors_strengthened=["Alerta, comunicación y protocolos ante eventos"],
        cobenefit_dimension_ids=[],
        cobenefit_note="El SAT fortalece capacidad de respuesta. No reduce la amenaza ni la sensibilidad biofísica por sí solo.",
        actors=[
            {"name": "Entidades de gestión del riesgo", "level": "riesgo"},
            {"name": "CORNARE", "level": "autoridad ambiental"},
            {"name": "Gobiernos municipales", "level": "municipal"},
            {"name": "Comunidades locales", "level": "comunitario"},
        ],
        limitations=["No es una solución basada en la naturaleza.", "Los puntos críticos del corredor no están listados."],
        nbs_reason="Instrumentación y protocolos. Medida habilitadora de la capacidad adaptativa.",
    ),
    _measure(
        id="risk_knowledge",
        name="Conocimiento y comunicación sobre amenazas, vulnerabilidad y riesgo climático",
        dimension_id="disaster",
        cost_million_cop=600,
        functional_unit="Estudios, modelación, instrumentación básica, protocolos y plataforma de información",
        type="risk_knowledge",
        nbs_class="ENABLING",
        scope="corridor",
        sensitivity_factors_addressed=[],
        adaptive_capacity_factors_strengthened=["Información, protocolos y comunicación del riesgo"],
        cobenefit_dimension_ids=[],
        cobenefit_note=None,
        actors=[
            {"name": "CORNARE", "level": "autoridad ambiental"},
            {"name": "Academia", "level": "conocimiento"},
            {"name": "Gobiernos municipales", "level": "municipal"},
            {"name": "Comunidades locales", "level": "comunitario"},
        ],
        limitations=["Produce información. No sustituye la reducción de sensibilidad en campo."],
        nbs_reason="Conocimiento y comunicación. Medida habilitadora.",
    ),
    _measure(
        id="health",
        name="Sistema de salud y entornos saludables resilientes al clima",
        dimension_id="health",
        cost_million_cop=800,
        functional_unit="Vigilancia climato-sensible, capacidades institucionales, prevención y respuesta",
        type="health_system",
        nbs_class="ENABLING",
        scope="municipality",
        sensitivity_factors_addressed=["Exposición de la salud a condiciones climáticas"],
        adaptive_capacity_factors_strengthened=["Vigilancia, prevención y respuesta institucional"],
        cobenefit_dimension_ids=[],
        cobenefit_note=None,
        actors=[
            {"name": "Instituciones de salud", "level": "salud"},
            {"name": "Gobiernos municipales", "level": "municipal"},
            {"name": "CORNARE", "level": "autoridad ambiental"},
        ],
        limitations=["No hay una línea base de morbilidad climática en el paquete."],
        nbs_reason="Capacidad del sistema de salud. No es una intervención ecosistémica.",
    ),
]


# Team inference: the lever each measure acts on, read from its factor lists.
# S = lowers sensitivity, CA = raises adaptive capacity. validate_inputs.py
# keeps this tag consistent with the two lists.
def lever_of(measure: dict) -> str:
    sensitivity = bool(measure["sensitivity_factors_addressed"])
    capacity = bool(measure["adaptive_capacity_factors_strengthened"])
    if sensitivity and capacity:
        return "S+CA"
    return "S" if sensitivity else "CA"


for _item in INTERVENTIONS:
    _item["lever"] = lever_of(_item)
    _item["lever_provenance"] = "team_inference"

# Published S and CA readings per municipality × dimension. Only these five
# cells have any number; the other 16 stay "sin desagregar" (missing, not low).
# The level words are the brief's wording; the profile is team inference.
LEVER_READINGS = [
    {
        "municipality_id": "rionegro",
        "dimension_id": "disaster",
        "sensitivity": {"value": 0.40, "level": "alta", "wording": "mayor sensibilidad del corredor", "source_metric_id": "rio-disaster-sensitivity"},
        "adaptive_capacity": {"value": 0.56, "level": "adecuada", "wording": "relativamente favorable", "source_metric_id": "rio-drm-ac"},
    },
    {
        "municipality_id": "marinilla",
        "dimension_id": "disaster",
        "sensitivity": None,
        "adaptive_capacity": {"value": 0.61, "level": "adecuada", "wording": "relativamente favorable", "source_metric_id": "mar-drm-ac"},
    },
    {
        "municipality_id": "rionegro",
        "dimension_id": "biodiversity",
        "sensitivity": None,
        "adaptive_capacity": {"value": 0.22, "level": None, "wording": "el reto no asigna clase a este valor", "source_metric_id": "rio-bio-ac"},
    },
    {
        "municipality_id": "marinilla",
        "dimension_id": "biodiversity",
        "sensitivity": None,
        "adaptive_capacity": {"value": 0.24, "level": None, "wording": "el reto no asigna clase a este valor", "source_metric_id": "mar-bio-ac"},
    },
    {
        "municipality_id": "guarne",
        "dimension_id": "biodiversity",
        "sensitivity": None,
        "adaptive_capacity": {"value": 0.33, "level": "baja", "wording": "sigue en categoría Baja", "source_metric_id": "gua-bio-ac"},
    },
]

INFORMATION_GAPS = [
    {
        "id": "gap-company-water",
        "missing_information": "Dependencia de cada organización respecto de una fuente, captación o acueducto",
        "why_it_matters": "Sin esa relación no se sabe si proteger una cabecera cubre a los usuarios productivos del corredor.",
        "which_decision_it_could_change": "Podría mover la protección de cabeceras o la eficiencia hídrica entre municipios, o justificar un segundo sistema abastecedor.",
        "how_to_collect_it": "Cruce, con las empresas de los Acuerdos de Crecimiento Verde y los acueductos, de captaciones autorizadas y usuarios. Solo datos agregados si la información es reservada.",
        "responsible_actor_if_known": "CORNARE, con acueductos y sectores productivos",
        "priority": "alta",
        "provenance": "institutional",
    },
    {
        "id": "gap-company-road",
        "missing_information": "Dependencia de organizaciones respecto de vías o puntos críticos de acceso",
        "why_it_matters": "La medida de infraestructura resiliente cuesta 2.500 millones y exige un punto crítico que el paquete no nombra.",
        "which_decision_it_could_change": "Podría incluir o excluir la infraestructura gris, y definir si el punto está en Guarne o en Rionegro.",
        "how_to_collect_it": "Inventario municipal de puntos críticos viales ya priorizados por gestión del riesgo, sin inventar la cadena logística de una empresa.",
        "responsible_actor_if_known": "Gobiernos municipales y entidades de gestión del riesgo",
        "priority": "alta",
        "provenance": "institutional",
    },
    {
        "id": "gap-suppliers",
        "missing_information": "Dependencia entre organizaciones y sus proveedores",
        "why_it_matters": "Una interrupción puede propagarse fuera del predio intervenido.",
        "which_decision_it_could_change": "Podría ampliar el alcance de una medida desde un municipio hacia un sistema productivo regional.",
        "how_to_collect_it": "Encuesta agregada y voluntaria a organizaciones de los Acuerdos de Crecimiento Verde sobre proveedores críticos, sin publicar identidades reservadas.",
        "responsible_actor_if_known": "CORNARE",
        "priority": "media",
        "provenance": "institutional",
    },
    {
        "id": "gap-energy",
        "missing_information": "Dependencia de redes de energía y de servicios públicos esenciales",
        "why_it_matters": "La medida de servicios públicos no tiene un servicio nombrado.",
        "which_decision_it_could_change": "Definiría si los 2.000 millones de servicios públicos entran al portafolio y sobre cuál servicio.",
        "how_to_collect_it": "Mapa de servicios esenciales ya identificado por los comités municipales de gestión del riesgo.",
        "responsible_actor_if_known": "Entidades de gestión del riesgo y empresas de servicios públicos",
        "priority": "alta",
        "provenance": "institutional",
    },
    {
        "id": "gap-ecosystem-service-sites",
        "missing_information": "Localización de los servicios ecosistémicos que cada medida usaría",
        "why_it_matters": "El catálogo opera a escala municipal o de corredor. Un mapa de sitios cambiaría la unidad real a intervenir.",
        "which_decision_it_could_change": "Podría concentrar restauración, rondas o cabeceras en un municipio distinto al que sugiere la clase de vulnerabilidad.",
        "how_to_collect_it": "Cruces con determinantes ambientales, POMCAS y áreas protegidas de CORNARE, a escala de microcuenca.",
        "responsible_actor_if_known": "CORNARE",
        "priority": "alta",
        "provenance": "team_inference",
    },
    {
        "id": "gap-workers",
        "missing_information": "Personas trabajadoras afectadas por interrupciones específicas",
        "why_it_matters": "El reto pide no inventar efectos sobre la operación empresarial.",
        "which_decision_it_could_change": "Podría elevar una medida habilitadora o de infraestructura si un grupo de trabajadores queda expuesto.",
        "how_to_collect_it": "Dato agregado de empleo expuesto, construido con las organizaciones y las alcaldías, sin microdatos reservados.",
        "responsible_actor_if_known": None,
        "priority": "media",
        "provenance": "institutional",
    },
    {
        "id": "gap-sites",
        "missing_information": "Sitio exacto de cada intervención",
        "why_it_matters": "Asignar un municipio no es asignar un predio, una quebrada o un punto de obra.",
        "which_decision_it_could_change": "El orden de implementación y el actor responsable de obra.",
        "how_to_collect_it": "Priorización espacial con los municipios usando POMCAS, rondas y puntos críticos ya oficiales.",
        "responsible_actor_if_known": "CORNARE y gobiernos municipales",
        "priority": "alta",
        "provenance": "team_inference",
    },
    {
        "id": "gap-effectiveness",
        "missing_information": "Efectividad de cada medida sobre sensibilidad, capacidad adaptativa o vulnerabilidad",
        "why_it_matters": "Sin ese coeficiente el puntaje no puede leerse como riesgo evitado.",
        "which_decision_it_could_change": "Podría reordenar el portafolio si una medida barata rinde poco o una medida costosa rinde mucho.",
        "how_to_collect_it": "Línea base y seguimiento MEA de resultado, no solo de actividades. La meta regional de −30% a 2035 no se reparte entre medidas.",
        "responsible_actor_if_known": "CORNARE, módulo MEA",
        "priority": "alta",
        "provenance": "team_inference",
    },
    {
        "id": "gap-hydrology",
        "missing_information": "Respuesta hidrológica local a restauración, rondas, cabeceras o SUDS",
        "why_it_matters": "No hay un modelo de inundación ni de caudal en este ejercicio.",
        "which_decision_it_could_change": "La elección entre SUDS, rondas y cabeceras dentro del recurso hídrico y el hábitat.",
        "how_to_collect_it": "Series de MARCO y estudios de POMCA ya existentes, sin construir un modelo nuevo para el prototipo.",
        "responsible_actor_if_known": "CORNARE",
        "priority": "media",
        "provenance": "team_inference",
    },
    {
        "id": "gap-maintenance",
        "missing_information": "Capacidad de mantenimiento después del costo inicial",
        "why_it_matters": "Restauración, SUDS y obras grises fallan si no hay quien las sostenga.",
        "which_decision_it_could_change": "Podría preferir medidas con actor de mantenimiento claro frente a una obra de 2.500 millones.",
        "how_to_collect_it": "Pregunta explícita a alcaldías, acueductos y administradores de áreas sobre presupuesto de operación.",
        "responsible_actor_if_known": "Gobiernos municipales",
        "priority": "media",
        "provenance": "team_inference",
    },
    {
        "id": "gap-workshops",
        "missing_information": "Recurrencia de cada medida en los talleres municipales",
        "why_it_matters": "La priorización institucional de CORNARE reserva 15% a ese criterio.",
        "which_decision_it_could_change": "Puede reordenar medidas con vulnerabilidad parecida cuando el 15% se pueda calificar.",
        "how_to_collect_it": "Conteo por medida y municipio a partir de las memorias de los talleres de la actualización de riesgos.",
        "responsible_actor_if_known": "CORNARE",
        "priority": "alta",
        "provenance": "institutional",
    },
    {
        "id": "gap-ssp-cube",
        "missing_information": "Serie de amenaza, sensibilidad, capacidad adaptativa, vulnerabilidad y riesgo para cada municipio, dimensión y escenario, incluido SSP3-7.0 a 2060",
        "why_it_matters": "Solo hay un cambio numérico de escenario: el riesgo de desastres de Rionegro.",
        "which_decision_it_could_change": "La prueba de robustez completa. Hoy la mayoría de dimensiones queda como evidencia insuficiente.",
        "how_to_collect_it": "Consulta del Observatorio Ambiental por subregión, índice, año, escenario y dimensión, y publicación de la tabla.",
        "responsible_actor_if_known": "CORNARE",
        "priority": "alta",
        "provenance": "institutional",
    },
    {
        "id": "gap-marinilla-coverage",
        "missing_information": "Cobertura del reporte de medidas de adaptación en Marinilla",
        "why_it_matters": "Marinilla tiene un solo registro. Eso no demuestra menor actividad de adaptación.",
        "which_decision_it_could_change": "El término de recurrencia de cualquier medida localizada en Marinilla.",
        "how_to_collect_it": "Completar PAI, PICCA y acciones municipales de Marinilla con la misma ficha de los otros municipios.",
        "responsible_actor_if_known": "CORNARE y municipio de Marinilla",
        "priority": "alta",
        "provenance": "team_inference",
    },
]

# Team inference, read from each gap's which_decision_it_could_change (to be
# confirmed with CORNARE). kind: dependency (a fact about who depends on what),
# site (where to build), model (a number the score uses).
NON_CORRIDOR_IDS = [item["id"] for item in INTERVENTIONS if item["scope"] != "corridor"]
GAP_LINKS = {
    "gap-company-water": ("dependency", ["water_head", "water_eff"]),
    "gap-company-road": ("dependency", ["infra_resilient"]),
    "gap-energy": ("dependency", ["infra_services"]),
    "gap-suppliers": ("dependency", ["food_agro", "food_soil"]),
    "gap-workers": ("dependency", ["infra_resilient", "infra_services", "risk_sat"]),
    "gap-ecosystem-service-sites": ("site", ["bio_restore", "water_riparian", "water_head"]),
    "gap-sites": ("site", NON_CORRIDOR_IDS),
    "gap-hydrology": ("model", ["hab_suds", "water_riparian", "water_head"]),
    "gap-maintenance": ("model", ["bio_restore", "hab_suds", "infra_resilient"]),
    "gap-marinilla-coverage": ("model", ["water_eff", "water_riparian", "water_head", "hab_green", "hab_suds", "health"]),
    "gap-effectiveness": ("model", [item["id"] for item in INTERVENTIONS]),
    "gap-workshops": ("model", [item["id"] for item in INTERVENTIONS]),
    "gap-ssp-cube": ("model", [item["id"] for item in INTERVENTIONS]),
}

for _gap in INFORMATION_GAPS:
    _kind, _ids = GAP_LINKS[_gap["id"]]
    _gap["kind"] = _kind
    _gap["affected_intervention_ids"] = list(_ids)
    _gap["affected_provenance"] = "team_inference"
