import { assetUrl } from '../assetUrl.js';
import { CASE_IDS, CASE_ROLES, EVIDENCE_CATEGORIES } from './caseTypes.js';

/** Medellín remains the deep primary proving ground. Default data paths unchanged. */
export const medellinCase = Object.freeze({
  id: CASE_IDS.MEDELLIN,
  city: 'Medellín',
  country: 'Colombia',
  displayName: 'Medellín — Primary proving ground',
  shortName: 'Medellín',
  focusArea: 'Llanaditas / Upper Comuna 8',
  caseType: CASE_ROLES.PRIMARY,
  areaId: 'llanaditas',
  hierarchyLabel: 'Primary proving ground',
  hierarchyBlurb: 'Steep vulnerable neighborhoods · local official data',
  contextLine: 'Steep vulnerable neighborhoods · local official data',
  introNotice: null,
  boundingArea: {
    sandboxBbox: [-75.541116, 6.250378, -75.53662, 6.25492],
    cityMaxBounds: [
      [-75.72, 6.12],
      [-75.43, 6.4],
    ],
    mapViews: {
      city: { center: [-75.572, 6.255], zoom: 12.2, pitch: 0, bearing: 0 },
      sandbox: {
        center: [-75.53887, 6.25265],
        zoom: 16.55,
        pitch: 36,
        bearing: -12,
      },
    },
  },
  dataPaths: Object.freeze({
    buildings: assetUrl('data/buildings.geojson'),
    roads: assetUrl('data/roads.geojson'),
    hazard: assetUrl('data/hazard.geojson'),
    cells: assetUrl('data/planning_cells.geojson'),
    summary: assetUrl('data/summary.json'),
    screening: assetUrl('data/medellin_city_priority_screen.geojson'),
    evidence: assetUrl('data/evidence_status.json'),
    climateContext: assetUrl('data/climate_context.json'),
    planAlignment: assetUrl('data/plan_alignment.json'),
    costContext: assetUrl('data/cost_context.json'),
    communityEvidence: assetUrl('data/community_evidence.json'),
    retrospective: null,
    retrospectiveComparison: null,
    dataManifest: null,
  }),
  availableDatasets: Object.freeze([
    'municipal_dem_1m',
    'official_mass_movement_hazard',
    'cadastral_buildings',
    'dane_population_proxy',
    'imcv_ampi',
    'chirps_v3',
    'official_access_network',
  ]),
  availablePlanningLenses: Object.freeze(['exposure', 'balanced', 'equity']),
  availableInterventionTypes: Object.freeze(['rwh', 'drainage', 'restoration']),
  objectiveProfileIds: Object.freeze(['balanced', 'equity', 'access', 'low_regret']),
  climateContextSource: 'CHIRPS v3.0 Final',
  terrainSource: 'Medellín 2024 municipal 1 m DEM (Terrain-RGB)',
  populationSource: 'DANE census-block planning proxy',
  evidenceProvenance: EVIDENCE_CATEGORIES.OBSERVED_REMOTE,
  scientificLimitations: Object.freeze([
    'Climate stress is not landslide probability.',
    'Population is a planning proxy, not a current household count.',
    'Intervention effects remain explicit planning priors.',
  ]),
  terminology: Object.freeze({
    hazardLayer: 'Mass-movement hazard',
    stressConcept: 'Climate stress (hillside susceptibility × rainfall context)',
    equityMetric: 'Stratum-1 exposure share',
    populationLabel: 'Census-based planning proxy',
  }),
  sourceAcknowledgements: Object.freeze([
    'Alcaldía de Medellín / DAGRD hazard and cadastral layers',
    'DANE population and socioeconomic products',
    'CHIRPS v3 Final (UCSB CHC)',
  ]),
  supportedMetrics: Object.freeze([
    'robust_benefit',
    'equity_benefit',
    'access_benefit',
    'p10_median_p90',
    'downside_retention',
    'selection_stability',
  ]),
  forbiddenClaims: Object.freeze([
    'landslide probability',
    'people saved or protected',
    'avoided losses',
    'community acceptance',
  ]),
  unsupportedFeatures: Object.freeze([]),
  interventionCopy: null,
  priorityCards: null,
  cityLenses: null,
  retrospectiveEvidence: Object.freeze([]),
  sandboxPlaceLabel: 'Llanaditas No.2 · Comuna 8 · Villa Hermosa',
  aerialImage: assetUrl('data/llanaditas_imagery.jpg'),
  usesEquityLens: true,
  usesCommunitySafeguards: true,
  screeningMode: 'barrio',
});
