import { assetUrl } from '../assetUrl.js';
import { CASE_IDS, CASE_ROLES, EVIDENCE_CATEGORIES } from './caseTypes.js';

const NANJING_PREFIX = 'data/nanjing';

/** Nanjing / Xianlin — portability demonstration only (not equal validation depth). */
export const nanjingCase = Object.freeze({
  id: CASE_IDS.NANJING,
  city: 'Nanjing',
  country: 'China',
  displayName: 'Nanjing — Portability demonstration',
  shortName: 'Nanjing (Xianlin)',
  focusArea: 'Xianlin / Qixia District',
  caseType: CASE_ROLES.PORTABILITY,
  areaId: 'xianlin',
  hierarchyLabel: 'Portability demonstration',
  hierarchyBlurb: 'Urban drainage screening · global/open data',
  contextLine: 'Urban drainage screening · global/open data',
  introNotice:
    'Portability demo with open data — not a hydraulic flood model.',
  boundingArea: {
    sandboxBbox: [118.88, 32.075, 118.97, 32.145],
    bboxStatus: 'initial reproducible screening bbox; not an official Xianlin administrative boundary',
    cityMaxBounds: [
      [118.85, 32.05],
      [119.0, 32.17],
    ],
    mapViews: {
      city: { center: [118.925, 32.11], zoom: 12.4, pitch: 0, bearing: 0 },
      sandbox: {
        center: [118.925, 32.11],
        zoom: 15.35,
        pitch: 42,
        bearing: 18,
      },
    },
  },
  dataPaths: Object.freeze({
    buildings: assetUrl(`${NANJING_PREFIX}/buildings.geojson`),
    buildingMassing: assetUrl(`${NANJING_PREFIX}/building_massing.geojson`),
    buildingMassingMeta: assetUrl(`${NANJING_PREFIX}/building_massing_meta.json`),
    roads: assetUrl(`${NANJING_PREFIX}/roads.geojson`),
    hazard: assetUrl(`${NANJING_PREFIX}/drainage_stress.geojson`),
    cells: assetUrl(`${NANJING_PREFIX}/planning_cells.geojson`),
    summary: assetUrl(`${NANJING_PREFIX}/summary.json`),
    screening: assetUrl(`${NANJING_PREFIX}/screening.geojson`),
    placeLabels: assetUrl(`${NANJING_PREFIX}/place_labels.geojson`),
    contextWater: assetUrl(`${NANJING_PREFIX}/context_water.geojson`),
    overviewMeta: assetUrl(`${NANJING_PREFIX}/overview_meta.json`),
    evidence: assetUrl(`${NANJING_PREFIX}/evidence_status.json`),
    climateContext: assetUrl(`${NANJING_PREFIX}/climate_context.json`),
    planAlignment: assetUrl(`${NANJING_PREFIX}/plan_alignment.json`),
    costContext: assetUrl(`${NANJING_PREFIX}/cost_context.json`),
    communityEvidence: null,
    retrospective: assetUrl(`${NANJING_PREFIX}/retrospective_validation.json`),
    dataManifest: assetUrl(`${NANJING_PREFIX}/data_manifest.json`),
    retrospectiveComparison: assetUrl(`${NANJING_PREFIX}/retrospective_comparison.json`),
  }),
  availableDatasets: Object.freeze([
    'mapzen_skadi_srtm',
    'nasa_power_daily_fallback',
    'worldpop_chn_2026',
    'esa_worldcover_2021',
    'osm_roads_waterways_optional',
  ]),
  availablePlanningLenses: Object.freeze([
    'exposure',
    'balanced',
    'runoff_stress',
    'low_regret_screen',
  ]),
  availableInterventionTypes: Object.freeze(['rwh', 'drainage', 'restoration']),
  objectiveProfileIds: Object.freeze([
    'balanced',
    'exposure_first',
    'runoff_reduction',
    'low_regret',
  ]),
  climateContextSource: 'NASA POWER Daily (credential-free IMERG fallback)',
  terrainSource: 'Mapzen Terrain Tiles / AWS Open Data (Skadi SRTM-style)',
  populationSource: 'WorldPop 2026 population estimate (China constrained ~100 m)',
  evidenceProvenance: EVIDENCE_CATEGORIES.OBSERVED_REMOTE,
  scientificLimitations: Object.freeze([
    'Adaptation screening only — not a hydraulic flood model.',
    'Terrain-derived drainage-stress indicators are screening proxies, not inundation maps.',
    'WorldPop values are population estimates, not census counts.',
    'No fabricated Chinese socioeconomic / equity layer.',
    'Official municipal projects are retrospective evidence only and never optimizer inputs.',
    'This case is not locally validated to Medellín depth.',
  ]),
  terminology: Object.freeze({
    hazardLayer: 'Terrain-derived drainage-stress screening proxy',
    stressConcept: 'Drainage-stress screening index × monsoon rainfall context',
    equityMetric: null,
    populationLabel: 'WorldPop 2026 population estimate',
  }),
  sourceAcknowledgements: Object.freeze([
    'Mapzen / Linux Foundation terrain tiles via AWS Open Data',
    'NASA POWER Daily API (climate-context fallback)',
    'WorldPop China 2026 constrained population (CC BY 4.0)',
    'ESA WorldCover 2021 v200 (CC BY 4.0)',
    'OpenStreetMap / Geofabrik where used (ODbL)',
    'Nanjing municipal sources for retrospective validation only',
  ]),
  supportedMetrics: Object.freeze([
    'robust_benefit',
    'access_benefit',
    'p10_median_p90',
    'downside_retention',
    'selection_stability',
  ]),
  forbiddenClaims: Object.freeze([
    'flood probability',
    'inundation depth',
    'hydraulic model',
    'people saved or protected',
    'avoided losses',
    'exact drainage capacity',
    'government or municipal endorsement',
    'validated across China',
    'exact household population',
    'calibrated runoff',
    'community acceptance',
    'Ourea discovered the 9,000 m³ facility',
  ]),
  unsupportedFeatures: Object.freeze([
    'equity_lens',
    'imcv_ampi',
    'community_safeguards',
    'stratum_weighting',
    'cadastral_building_counts',
  ]),
  interventionCopy: Object.freeze({
    rwh: {
      label: 'Rainwater storage / harvesting',
      mechanism: 'Capture roof and parcel runoff before it loads local drainage.',
      evidence: 'Planning assumption for monsoon urban drainage; effect remains an explicit prior.',
    },
    drainage: {
      label: 'Drainage / water-management upgrade',
      mechanism: 'Improve conveyance and reduce local ponding stress where corridors allow.',
      evidence: 'Screening corridor proxy from terrain and land cover; not a capacity design.',
    },
    restoration: {
      label: 'Green infrastructure / soil-water retention',
      mechanism: 'Increase vegetated retention and slow runoff on mixed hilly–lowland terrain.',
      evidence: 'WorldCover vegetation opportunity proxy; effect remains an explicit planning prior.',
    },
  }),
  priorityCards: Object.freeze({
    balanced: {
      name: 'Balanced',
      description: 'Balance exposure and runoff pressure.',
      how: 'Keeps drainage-stress exposure reduction first, with light access weight. No equity layer.',
    },
    exposure_first: {
      name: 'Exposure-first',
      description: 'Prioritize exposed population.',
      how: 'Zero equity weight; emphasizes population-weighted residual stress reduction.',
    },
    runoff_reduction: {
      name: 'Drainage stress',
      description: 'Prioritize drainage-stress signals.',
      how: 'Raises access/drainage-corridor weight so water-management and retention actions compete strongly.',
    },
    low_regret: {
      name: 'Low-regret',
      description: 'Prefer areas that hold up when assumptions change.',
      how: 'Strong downside penalty; same uncertainty engine as Medellín.',
    },
  }),
  cityLenses: Object.freeze({
    exposure: {
      label: 'Exposure',
      rankField: 'rank_exposure',
      scoreField: 'priority_exposure',
      question: 'Prioritize exposed population',
      description: 'Population estimate × drainage-stress screening proxy.',
    },
    balanced: {
      label: 'Balanced',
      rankField: 'rank_balanced',
      scoreField: 'priority_balanced',
      question: 'Balance exposure and runoff pressure',
      description: 'Mixes exposure with built-up / runoff-pressure proxy.',
    },
    runoff_stress: {
      label: 'Drainage stress',
      rankField: 'rank_runoff',
      scoreField: 'priority_runoff',
      question: 'Prioritize drainage-stress signals',
      description: 'Terrain drainage-stress screening proxies — not inundation depth.',
    },
    low_regret_screen: {
      label: 'Low-regret',
      rankField: 'rank_low_regret',
      scoreField: 'priority_low_regret',
      question: 'Prefer areas supported by multiple signals',
      description: 'Consensus of exposure, built-up pressure and drainage-stress ranks.',
    },
  }),
  objectiveProfiles: Object.freeze({
    balanced: {
      label: 'Balanced',
      description: 'Balances robust exposure reduction with modest access weighting. Equity disabled.',
      equityWeight: 0,
      accessWeight: 0.15,
      downsidePenalty: 0.55,
    },
    exposure_first: {
      label: 'Exposure-first',
      description: 'Prioritizes population-weighted drainage-stress reduction.',
      equityWeight: 0,
      accessWeight: 0.05,
      downsidePenalty: 0.55,
    },
    runoff_reduction: {
      label: 'Runoff / drainage-stress reduction',
      description: 'Emphasizes cells supporting drainage and retention opportunity.',
      equityWeight: 0,
      accessWeight: 1.0,
      downsidePenalty: 0.55,
    },
    low_regret: {
      label: 'Low-regret',
      description: 'Penalizes lower-tail uncertainty strongly.',
      equityWeight: 0,
      accessWeight: 0.15,
      downsidePenalty: 1.5,
    },
  }),
  retrospectiveEvidence: Object.freeze([
    {
      id: 'qixia_official_topography',
      title: 'Qixia mixed terrain (south-high / north-low)',
      source: 'Qixia District Government',
      url: 'https://www.njqxq.gov.cn/sjb2018/ssqx/qxgk/index.html',
      claim:
        'Southern Qixia is hilly/upland (commonly 50–300 m); northern Yangtze plain/islands generally below 10 m.',
      optimizer_input: false,
      category: EVIDENCE_CATEGORIES.OFFICIAL_MUNICIPAL,
    },
    {
      id: 'xianlin_yuanhua_xianyin_2026',
      title: 'Yuanhua Road / Xianyin North Road waterlogging remediation (2026)',
      source: 'Nanjing Public Resources Trading Center',
      url: 'https://njggzy.nanjing.gov.cn/njweb/jtsw/069005/069005001/20260306/f9f67762-9758-45d8-a898-d801ed8720f7.html',
      claim:
        'Official 2026 waterlogging-remediation works in Xianlin including new stormwater pipe and cleaning/repair.',
      optimizer_input: false,
      category: EVIDENCE_CATEGORIES.OFFICIAL_MUNICIPAL,
    },
    {
      id: 'hengyang_jiuxiang_storage',
      title: 'Jiuxiang River / Hengyang Lake 9,000 m³ detention storage',
      source: 'Nanjing Water Affairs Bureau',
      url: 'https://shuiwu.nanjing.gov.cn/njsswj/202501/t20250122_5063584.html',
      claim:
        'Official detention/storage facility with 9,000 m³ effective volume intended in part to reduce Xianlin/Jiuxianghe-area waterlogging risk.',
      optimizer_input: false,
      category: EVIDENCE_CATEGORIES.OFFICIAL_MUNICIPAL,
    },
    {
      id: 'nanjing_water_plan_2026_2030',
      title: 'Nanjing municipal water / waterlogging policy context (2026–2030)',
      source: 'Nanjing Municipal Government',
      url: 'https://www.nanjing.gov.cn/zdgk/202608/t20260807_5890796.html',
      claim:
        'Municipal plan calls for continued urban waterlogging remediation and drainage upgrades, including Qixia areas.',
      optimizer_input: false,
      category: EVIDENCE_CATEGORIES.OFFICIAL_MUNICIPAL,
    },
  ]),
  sandboxPlaceLabel: 'Xianlin · Qixia District · Nanjing (screening AOI)',
  aerialImage: null,
  usesEquityLens: false,
  usesCommunitySafeguards: false,
  screeningMode: 'overview',
  stepAreaInstruction: 'Xianlin is the detailed case. Nearby areas provide context.',
  legendCityTitle: 'Screening priority',
  legendCityNote: 'Named areas and screening sectors',
  legendSandboxTitle: 'Screening condition',
  legendSandboxNote: null,
  legendSandboxBaselineNote: 'Baseline · selected rainfall',
  legendSandboxResidualNote: 'After plan · residual condition',
  detailGridNote: 'Detailed analysis uses 80 planning cells.',
});
